version: "3"
services:

  backend:
      image: garugaru/magnete
      ports:
        - 9999:80
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 5s
        restart_policy:
          condition: on-failure