version: "3"
services:

  magnete:
      image: garugaru/magnete
      ports:
        - 9999:80
      environment:
        - GIN_MODE=release
        - TIMEOUT=60s
      deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 5s
        restart_policy:
          condition: on-failure